version: '3.8'

volumes:
  postgres:

services:
  fastapi-db:
    build: ./database
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./database:/workspace/database
      - ./database/initdb:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
